spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/fornecedor?createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true
